alias f='nnn'
alias v='nvim'
alias n='nvim'
alias mkdir='mkdir -p'
alias ls='exa --color=always --group-directories-first --icons'
alias ll='exa --color=always --group-directories-first --long --icons'
alias lt='exa --color=always --group-directories-first --tree --icons'
alias la='exa --color=always --group-directories-first --all --icons'
alias cat='bat'
alias gt='git clone'
alias data='cd /data'
alias repos='cd /data/Repos'
alias scripts='cd /data/Scripts'
alias fzf='fzf --cycle --height=20% --layout=reverse --border=rounded --margin=5%'
alias tx='latexmk -pdf -pvc'
alias yt='youtube-dl'
alias mput='ampy --port /dev/ttyUSB0 --baud 115200 put'
alias mls='ampy --port /dev/ttyUSB0 --baud 115200 ls'
alias mrun='ampy --port /dev/ttyUSB0 --baud 115200 run'
alias pi='sudo pacman -S --noconfirm'
alias ps='sudo pacman -Ss'
alias pr='sudo pacman -Rscn --noconfirm'
alias pu='sudo pacman -Syuu --noconfirm'
alias pai='paru -S'
alias pau='paru -Syuu'
alias pas='paru -Ss'
alias gnome-arrange='gsettings reset org.gnome.shell app-picker-layout'
