alias f='ranger'
alias mkdir='mkdir -p'
alias ls='exa --color=always --group-directories-first'
alias lt='exa --color=always --group-directories-first --tree'
alias la='exa --color=always --group-directories-first --all'
alias cat='bat'
alias ai='sudo apt install -y'
alias as='sudo apt search'
alias ar='sudo apt remove -y'
alias ap='sudo apt autopurge -y'
alias au='sudo apt update -y && sudo apt upgrade -y'
alias gt='git clone'
alias data='cd /data'
alias repos='cd /data/Repos'
alias scripts='cd /data/Scripts'
alias fzf='fzf --cycle --height=20% --layout=reverse --border=rounded --margin=5%'
