alias f='nnn'
alias mkdir='mkdir -p'
alias ls='exa --color=always --group-directories-first --icons'
alias ll='exa --color=always --group-directories-first --long --icons'
alias lt='exa --color=always --group-directories-first --tree --icons'
alias la='exa --color=always --group-directories-first --all --icons'
alias cat='bat'
alias catt='cat'
alias gt='git clone'
alias fzf='fzf --cycle --height=20% --layout=reverse --border=rounded --margin=5%'
alias mput='ampy --port /dev/ttyUSB0 --baud 115200 put'
alias mls='ampy --port /dev/ttyUSB0 --baud 115200 ls'
alias mrun='ampy --port /dev/ttyUSB0 --baud 115200 run'
alias ua='sudo dnf update -y ; flatpak update -y'
alias ds='sudo dnf search'
alias dr='sudo dnf remove -y'
